eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
server:
  port: 10001
spring:
  application:
    name: zuul
##配置zuul网关
zuul:
  routes:
    api-a:
      path: /member-zuul/**
      service-id: member-server
    api-b:
      path: /order-zuul/**
      service-id: order-server

